/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Compile Vue template to VDom render function */
export declare function compile(template: string, options?: CompilerOptions | undefined | null): CompileResult
/** Compile Vue template to Vapor mode */
export declare function compileVapor(template: string, options?: CompilerOptions | undefined | null): CompileResult
/** Parse template to AST only */
export declare function parseTemplate(template: string, options?: CompilerOptions | undefined | null): any
/** SFC parse options for NAPI */
export interface SfcParseOptionsNapi {
  filename?: string
}
/** SFC compile options for NAPI */
export interface SfcCompileOptionsNapi {
  filename?: string
  sourceMap?: boolean
  ssr?: boolean
}
/** SFC compile result for NAPI */
export interface SfcCompileResultNapi {
  /** Generated JavaScript code */
  code: string
  /** Generated CSS (if any) */
  css?: string
  /** Compilation errors */
  errors: Array<string>
  /** Compilation warnings */
  warnings: Array<string>
}
/** Parse SFC (.vue file) - returns lightweight result for speed */
export declare function parseSfc(source: string, options?: SfcParseOptionsNapi | undefined | null): object
/** Compile SFC (.vue file) to JavaScript - main use case */
export declare function compileSfc(source: string, options?: SfcCompileOptionsNapi | undefined | null): SfcCompileResultNapi
/** Batch compile options for NAPI */
export interface BatchCompileOptionsNapi {
  ssr?: boolean
  threads?: number
}
/** Batch compile result for NAPI */
export interface BatchCompileResultNapi {
  /** Number of files compiled successfully */
  success: number
  /** Number of files that failed */
  failed: number
  /** Total input bytes */
  inputBytes: number
  /** Total output bytes */
  outputBytes: number
  /** Compilation time in milliseconds */
  timeMs: number
}
/** Batch compile SFC files matching a glob pattern (native multithreading) */
export declare function compileSfcBatch(pattern: string, options?: BatchCompileOptionsNapi | undefined | null): BatchCompileResultNapi
/** Compiler options for bindings */
export interface CompilerOptions {
  /** Output mode: "module" or "function" */
  mode?: string
  /** Whether to prefix identifiers */
  prefixIdentifiers?: boolean
  /** Whether to hoist static nodes */
  hoistStatic?: boolean
  /** Whether to cache event handlers */
  cacheHandlers?: boolean
  /** Scope ID for scoped CSS */
  scopeId?: string
  /** Whether in SSR mode */
  ssr?: boolean
  /** Whether to generate source map */
  sourceMap?: boolean
  /** Filename for source map */
  filename?: string
  /** Output mode: "vdom" or "vapor" */
  outputMode?: string
  /** Whether the template contains TypeScript */
  isTs?: boolean
}
/** Compile result */
export interface CompileResult {
  /** Generated code */
  code: string
  /** Preamble code (imports) */
  preamble: string
  /** AST (serialized as JSON) */
  ast: any
  /** Source map */
  map?: any
  /** Used helpers */
  helpers: Array<string>
  /** Template strings for Vapor mode static parts */
  templates?: Array<string>
}
